import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata = {
  title: "Evans Maina",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} antialiased bg-[#000101] min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
